### ISSUE TITLE
support for blender 2.8

### ISSUE THREAD

**Issue by zhezh** [SarahWeiii/Blender_cv#1]
Hi, I am using blender 2.8 on ubuntu,
and I follow your instruction to install and run blcv, below error occurs:

```
Traceback (most recent call last):
  File "/data/projects/Blender_cv/blender_script.py", line 70, in <module>
    main()
  File "/data/projects/Blender_cv/blender_script.py", line 67, in main
    get_images_for_model(model.replace('\\', '/'), view_params, os.path.join(BASE_DIR, 'images'))
  File "/data/projects/Blender_cv/blender_script.py", line 32, in get_images_for_model
    scene.set_render_mode('TRANSPARENT')
  File "/data/projects/Blender_cv/blcv/tools.py", line 170, in set_render_mode
    bpy.context.scene.render.alpha_mode = mode
AttributeError: 'RenderSettings' object has no attribute 'alpha_mode'
```

I suspect this is because new version blender has changed its apis.
Could you please update blcv to be compatible with newer version
Thanks

**Comment by SarahWeiii** [comment]
> Hi, I am using blender 2.8 on ubuntu,
> and I follow your instruction to install and run blcv, below error occurs:
> 
> ```
> Traceback (most recent call last):
>   File "/data/projects/Blender_cv/blender_script.py", line 70, in <module>
>     main()
>   File "/data/projects/Blender_cv/blender_script.py", line 67, in main
>     get_images_for_model(model.replace('\\', '/'), view_params, os.path.join(BASE_DIR, 'images'))
>   File "/data/projects/Blender_cv/blender_script.py", line 32, in get_images_for_model
>     scene.set_render_mode('TRANSPARENT')
>   File "/data/projects/Blender_cv/blcv/tools.py", line 170, in set_render_mode
>     bpy.context.scene.render.alpha_mode = mode
> AttributeError: 'RenderSettings' object has no attribute 'alpha_mode'
> ```
> 
> I suspect this is because new version blender has changed its apis.
> Could you please update blcv to be compatible with newer version
> Thanks

Hi, thanks for the suggestion. There are indeed some differences between blender 2.7.9 and 2.8, I will find some time to update the code.

**Comment by zhezh** [comment]
It's great
